# Generated by Django 5.0.3 on 2024-03-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='media_type',
            field=models.CharField(default='video/ogg', max_length=200),
            preserve_default=False,
        ),
    ]
