# Generated by Django 5.0.3 on 2024-03-17 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_uploadedfile_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
