# Generated by Django 5.0.3 on 2024-03-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_uploadedfile_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='size',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
