# Generated by Django 5.0.3 on 2024-03-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_uploadedfile_duration_uploadedfile_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='transcript',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
