# Generated by Django 5.0.3 on 2024-03-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_uploadedfile_options_uploadedfile_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='transcript',
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('language', models.CharField(max_length=20)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.uploadedfile')),
            ],
        ),
    ]
